name: Full DevSecOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build & Test
      run: mvn clean verify

    - name: SonarQube Scan
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=train-ticket-reservation \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Publish to Nexus
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>nexus</id>
              <username>${{ secrets.NEXUS_USERNAME }}</username>
              <password>${{ secrets.NEXUS_PASSWORD }}</password>
            </server>
          </servers>
        </settings>
        EOF

        mvn deploy \
        -DskipTests \
        -DaltDeploymentRepository=nexus::default::${{ secrets.NEXUS_URL }}/repository/${{ secrets.NEXUS_REPOSITORY }}/

    - name: Deploy to Tomcat
      run: |
        curl -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
        -T target/*.war \
        "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/myapp&update=true"
